sudo: required

language: ruby

services:
  - docker

before_install:
  - gem install serverspec
  - gem install docker-api
  - docker build -t test .

script:
  - IMAGEID=$(docker ps -q test) rspec Dockerfile_spec.rb
